/*
 * Filename: swc_engine.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: SWC for engine
 * name: swc_engine
 * shortname: engine
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_engine.h"



/* USER CODE START SWC_ENGINE_INCLUDE */

/* USER CODE END SWC_ENGINE_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_ENGINE_USERDEFINITIONS */

/* USER CODE END SWC_ENGINE_USERDEFINITIONS */



/*
 * component: swc_engine
 * cycletime: 100
 * description: Runnable to copy incoming speed signal to engine and call pushPort()
 * events: 
 * name: ENGINE_set_engine_run
 * shortname: set_engine
 * signalIN: so_speed
 * signalOUT: so_engine
 * task: tsk_io
 */
void ENGINE_set_engine_run(RTE_event ev){
	
	/* USER CODE START ENGINE_set_engine_run */

    SC_SPEED_data_t speed = SC_SPEED_INIT_DATA;
    static uint32_t speed_age = 0;
    SC_ENGINE_data_t engine = SC_ENGINE_INIT_DATA;
    
    if(RTE_SC_SPEED_getStatus(&SO_SPEED_signal) == RTE_SIGNALSTATUS_VALID)
    {
        speed.speed_value = RTE_SC_SPEED_get(&SO_SPEED_signal).speed_value;
    }
    
    speed_age = RTE_SC_SPEED_getAge(&SO_SPEED_signal);
    if(speed_age < 100)
    {
        engine.engine_value = speed.speed_value;
    }
    else{
        engine.engine_value = 0;
    }
    RTE_SC_ENGINE_set(&SO_ENGINE_signal, engine);
    RTE_SC_ENGINE_pushPort(&SO_ENGINE_signal);
    WD_Alive(engine_run);
    /* USER CODE END ENGINE_set_engine_run */
}

/* USER CODE START SWC_ENGINE_FUNCTIONS */

/* USER CODE END SWC_ENGINE_FUNCTIONS */

