/*
 * Filename: swc_brakelight.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: SWC for brakelight
 * name: swc_brakelight
 * shortname: brakelight
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "swc_brakelight.h"



/* USER CODE START SWC_BRAKELIGHT_INCLUDE */

/* USER CODE END SWC_BRAKELIGHT_INCLUDE */


#include "sp_common.h"

/* USER CODE START SWC_BRAKELIGHT_USERDEFINITIONS */

/* USER CODE END SWC_BRAKELIGHT_USERDEFINITIONS */



/*
 * component: swc_brakelight
 * cycletime: 0
 * description: Runnable to set brakelight if speed signal is 0
 * events: ev_on_speed_update
 * name: BRAKELIGHT_set_brakelight_run
 * shortname: set_brakelight
 * signalIN: so_speed
 * signalOUT: so_brakelight
 * task: tsk_io
 */
void BRAKELIGHT_set_brakelight_run(RTE_event ev){
	
	/* USER CODE START BRAKELIGHT_set_brakelight_run */

    SC_SPEED_data_t speed = SC_SPEED_INIT_DATA;
    if(RTE_SC_SPEED_getStatus(&SO_SPEED_signal) == RTE_SIGNALSTATUS_VALID)
    {
        speed = RTE_SC_SPEED_get(&SO_SPEED_signal);
    }    
    SC_BRAKELIGHT_data_t brakelight = SC_BRAKELIGHT_INIT_DATA;
    if(speed.speed_value == 0) brakelight.brakelight_value = TRUE; 
    else brakelight.brakelight_value = FALSE; 
    
    RTE_SC_BRAKELIGHT_set(&SO_BRAKELIGHT_signal, brakelight);
    RTE_SC_BRAKELIGHT_pushPort(&SO_BRAKELIGHT_signal);
    WD_Alive(brakelight_run);
    /* USER CODE END BRAKELIGHT_set_brakelight_run */
}

/* USER CODE START SWC_BRAKELIGHT_FUNCTIONS */

/* USER CODE END SWC_BRAKELIGHT_FUNCTIONS */

