/*
 * Filename: tsk_io.c
 *
 * Author: Autogenerated by H-DA RTE Generator, (c) Prof. Fromm
 *
 * description: Task for IO operations - joystick, engine, brakelight
 * events: ev_1ms|ev_on_speed_update
 * mode: Cyclic and Event
 * name: tsk_io
 * shortname: io
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_1ms
 * timertickperiod: 1
 *
 */

#include "project.h"
#include "global.h"
#include "rte.h"
#include "rte_types.h"
#include "tsk_io.h"



/* USER CODE START TSK_IO_INCLUDE */

/* USER CODE END TSK_IO_INCLUDE */

#include "swc_joystick.h"
#include "swc_engine.h"
#include "swc_brakelight.h"



/* USER CODE START TSK_IO_USERDEFINITIONS */

/* USER CODE END TSK_IO_USERDEFINITIONS */

/*******************************************************************************
 * Runnable Tables from Activation Engine
 *******************************************************************************/

/* Cyclic Table */

const RTE_cyclicTable_t RTE_cyclicActivationTable_tsk_io[] = {
	{ JOYSTICK_joystick_rx_run, 10 },	//Runnable to update joystick signal through pullPort()
	{ ENGINE_set_engine_run, 100 },	//Runnable to copy incoming speed signal to engine and call pushPort()
};
const uint16_t RTE_cyclicActivation_tsk_io_size = sizeof (RTE_cyclicActivationTable_tsk_io) / sizeof(RTE_cyclicTable_t); 

/* Event Table */
const RTE_eventTable_t RTE_eventActivationTable_tsk_io[] = {
    { BRAKELIGHT_set_brakelight_run, ev_on_speed_update },  //Runnable to set brakelight if speed signal is 0
}; 
const uint16_t RTE_eventActivation_tsk_io_size = sizeof (RTE_eventActivationTable_tsk_io) / sizeof(RTE_eventTable_t);

/*******************************************************************************
 * Task Body
 *******************************************************************************/


/*
 * description: Task for IO operations - joystick, engine, brakelight
 * events: ev_1ms|ev_on_speed_update
 * mode: Cyclic and Event
 * name: tsk_io
 * shortname: io
 * signalpoolsRO: sp_common
 * signalpoolsRW: sp_common
 * tickEvent: ev_1ms
 * timertickperiod: 1
 */
TASK(tsk_io)
{
	/* ticktime of the task */
	uint32_t ticktime = 0;
	
    EventMaskType ev = 0;
	
	/* USER CODE START TSK_IO_INIT */

	/* USER CODE END TSK_IO_INIT */
    
    while(1)
    {
        //Wait, read and clear the event
        WaitEvent(ev_1ms|ev_on_speed_update);
        GetEvent(tsk_io,&ev);
        ClearEvent(ev);
    
		/* USER CODE START TSK_IO_TASKBOBY_PRE */

		/* USER CODE END TSK_IO_TASKBODY_PRE */
        
        if (ev & ev_1ms){
            //Process Cyclic table on tick
            RTE_ProcessCyclicTable(RTE_cyclicActivationTable_tsk_io, RTE_cyclicActivation_tsk_io_size, ticktime);

			ticktime += 1;
			if (ticktime > 0xFFFFFF00) ticktime = 0;

		};
		
		//Process data driven events
		RTE_ProcessEventTable(RTE_eventActivationTable_tsk_io, RTE_eventActivation_tsk_io_size, ev);
		
		/* USER CODE START TSK_IO_TASKBODY_POST */

		/* USER CODE END TSK_IO_TASKBODY_POST */
        
    }
	
	//Just in Case
	TerminateTask();
}


/*******************************************************************************
 * Interrupt Service Routines
 *******************************************************************************/

/* USER CODE START TSK_IO_ISR */

/* USER CODE END TSK_IO_ISR */

